Bulk ingest
JupiterOne/graph-jira pull request #120
Opened 2021-11-17 21:50 UTC by kevincasey1222

Hi @aiwilliams and @austinkelleher !

Here is a PR to remove the limit on bulk ingestion according to a boolean config variable. It also includes retry logic, better error handling, respect for rate limits, and a trap around errors on Issues so that a problem with one Issue doesn't fail the step.

Side note: Though we thought the old code had a limit of 2000, it actually had a flaw that meant the real limit has been 500. This code fixes that, so the limit is now 2000 Issues without the boolean, or unlimited** with the bulkIngest boolean.

** until it crashes from running too long. :)

2021-11-18 02:56 UTC, aiwilliams requested changes

2021-11-18 02:56 UTC, aiwilliams commented on src/utils/builders.test.ts
> +  it('project configs from with blank extras', () => {
```suggestion
  it('project configs from array with blank extras', () => {
```

2021-11-18 02:56 UTC, aiwilliams commented on src/utils/builders.ts
> +export function buildProjectConfigs(projects: any): ProjectConfig[] {
What drove the need for these changes? Is there a related Jira issue? Ideally this could be a separate PR, to isolate the changes and in case there is a need to revert changes for bulk ingest.

2021-11-18 02:56 UTC, aiwilliams commented on src/utils/builders.test.ts
> +describe('produceProperProjectConfigsFromVariousInput', () => {
```suggestion
describe('buildProjectConfigs', () => {
```

2021-11-18 02:56 UTC, aiwilliams commented on src/steps/issues.ts
> +          if (issue.fields.creator && issue.fields.creator.accountId) {
Will this work?
```suggestion
          if (issue.fields.creator?.accountId) {
```

2021-11-18 02:56 UTC, aiwilliams commented on src/steps/issues.ts
> +          if (issue.fields.reporter && issue.fields.reporter.accountId) {
```suggestion
          if (issue.fields.reporter?.accountId) {
```

2021-11-18 02:56 UTC, aiwilliams commented on src/steps/issues.ts
> +              );
We should avoid `logger.warn` unless we intend to monitor and do something about these log events.
```suggestion
              logger.info(
                { creatorUserKey, issueName: issueEntity.name },
                '[SKIP] user_created_issue relationship, issue creator not found',
              );
```
Similar changes are necessary for other parts of this file.

2021-11-18 02:56 UTC, aiwilliams commented on src/steps/issues.ts
> +          logger.warn(err, `Error encountered on issue ${issue.id}`);
This is a good use of `logger.warn` because we should monitor these to discover when there are a significant number of failures.
```suggestion
          logger.warn({ err, issueId: issue.id }, 'Error encountered processing issue');
```

2021-11-18 02:56 UTC, aiwilliams commented on src/jira/createJiraClient.ts
> +  );
We aim to put the logger at the front, but perhaps better would be to make this function take a `{ config: TypeHere, logger: IntegrationLogger }`. Is there a reason the function has no type for the `config` (currently `any`)?

2021-11-18 02:56 UTC, aiwilliams commented on src/jira/__recordings__/steps_741716276/recording.har
> +            "text": "{\"errorMessages\":[\"The value 'key' does not exist for the field 'project'.\"],\"warningMessages\":[]}"
Are all these response errors expected? Are there new tests intentionally causing these?

2021-11-18 02:56 UTC, aiwilliams commented on src/jira/JiraClient.ts
> +      ) {
I didn't notice any new tests for the client, but I may be missing something. Where is the `Retry-After` header being extracted from the request headers and put into this `error`?

2021-11-24 17:31 UTC, kevincasey1222 commented on src/client.ts
> +          )
So glad you asked this. Just like in GitHub, this was legacy code that I hadn't questioned closely enough or properly recognized how it would interact with my new error handling code. It was broken on several levels.

Yes, we can use err.message here
Also, the if-clause needed an update to actually trigger and capture the error
And, the retry code needed to recognize this as unrecoverable

2021-11-24 18:12 UTC, kevincasey1222 commented on src/client.ts
> +          throw err;
If the error is 400, 401, 403, or 404, I don't think the next page will be any better.

If the error is not one of those, then we've already retried this page 4 times. That also makes me think that the next page won't be any better. 

The only thing changing in the request between pages is the `startAt` property.

2021-11-24 18:14 UTC, kevincasey1222 commented on src/client.ts
> +    if (issuesProcessed >= MAX_ISSUES_TO_INGEST) {
Yes, good catch

2021-11-24 18:16 UTC, kevincasey1222 commented on CHANGELOG.md
> +- Added Issue class to `jira_issue` entities
It's actually already in another PR, https://github.com/JupiterOne/graph-jira/pull/118

That one's been approved - it just needs a merge

2021-11-24 18:19 UTC, kevincasey1222 commented on src/config.ts
> -  }
It's in `util/buildProjectConfigs.ts`, which was already being called everywhere `config.projects` was referenced because it was doing some additional data grooming. Once I realized that, I just moved this functionality into that utility.

2021-11-24 18:21 UTC, kevincasey1222 commented on CHANGELOG.md
> +  if the step runs for more than 24 hours.
Okay. Changed.

2021-11-24 18:32 UTC, kevincasey1222 commented on CHANGELOG.md
> +- Counting Issues properly to respect MAX_ISSUES_TO_INGEST where applicable
Great. Done.

2021-11-24 18:33 UTC, kevincasey1222 commented on src/utils/builders.test.ts
> +  it('project configs from with blank extras', () => {
Thanks, good catch

2021-11-24 18:35 UTC, kevincasey1222 commented on src/utils/builders.ts
> +export function buildProjectConfigs(projects: any): ProjectConfig[] {
These are actually not behavior changes - just refactoring. `builders.ts` already existed, and because I didn't realize it when I did the SDK port months ago, I was also doing config mutation in `config.ts`. So, I consolidated the manipulation into `builders.ts` and wrote tests to cover all the scenarios that were previously being handled separately in those two places.

2021-11-24 18:36 UTC, kevincasey1222 commented on src/utils/builders.test.ts
> +describe('produceProperProjectConfigsFromVariousInput', () => {
Done.

2021-11-24 18:50 UTC, kevincasey1222 commented on CHANGELOG.md
> +- Added Issue class to `jira_issue` entities
I had Austin merge that old PR. So that's done.

2021-11-24 18:50 UTC, kevincasey1222 commented on src/steps/issues.ts
> +          if (issue.fields.creator && issue.fields.creator.accountId) {
Yes, done. Thanks.

2021-11-24 18:50 UTC, kevincasey1222 commented on src/steps/issues.ts
> +          if (issue.fields.reporter && issue.fields.reporter.accountId) {
Yes, thanks for the catch.

2021-11-24 18:53 UTC, kevincasey1222 commented on src/steps/issues.ts
> +              );
Gotcha. I like this update. Thanks. Now that I've watched you and Austin use Cloudwatch more, these kinds of improvements are making more sense to me.

2021-11-24 18:53 UTC, kevincasey1222 commented on src/steps/issues.ts
> +          logger.warn(err, `Error encountered on issue ${issue.id}`);
Done.

2021-11-24 20:13 UTC, kevincasey1222 commented on src/jira/createJiraClient.ts
> +  );
Cool, updated the type of config to { jiraHost: string; jiraUsername: string; jiraPassword: string; }

2021-11-24 20:16 UTC, kevincasey1222 commented on src/jira/__recordings__/steps_741716276/recording.har
> +            "text": "{\"errorMessages\":[\"The value 'key' does not exist for the field 'project'.\"],\"warningMessages\":[]}"
Yes, exactly. The tests are causing these errors purposefully for unit tests. I think they might actually have been hand-crafted.

2021-11-24 20:44 UTC, kevincasey1222 commented on src/jira/JiraClient.ts
> +      ) {
Sorry, you're right, this was incomplete, a placeholder I never returned to. Fixed.

2021-11-26 21:23 UTC, aiwilliams reviewed
@austinkelleher I think it would be good to run this locally against our Jira account to see how it goes with a large Jira instance.

2021-12-09 21:21 UTC, aiwilliams commented on src/client.ts
> +      (this.config.bulkIngest || issuesProcessed < MAX_ISSUES_TO_INGEST)
> If the integration is executing for the first time, this means that it will attempt to ingest all Issues in the account.

I don't quite understand how bulk ingestion is limited to the first execution. This looks like when `bulkIngest: true`, we'll keep going.

2021-12-10 16:37 UTC, kevincasey1222 commented on src/jira/JiraClient.ts
> +    factor: 2, //exponential backoff factor
Added.

2021-12-10 20:55 UTC, aiwilliams approved these changes

2021-12-10 20:56 UTC, merged