App 12341 pass action properties via s3
JupiterOne/graph-jira pull request #192
Opened 2023-05-02 18:58 UTC by plfx

# Description

Adds a path to invoke the CREATE_ENTITY action with Jira issue properties in an S3 object. This enables us to work around the AWS Lambda payload size limit of 6mb.

## Summary

- Changed `CreateIssueActionProperties` to a union type representing backward-compatible and new S3-backed invocation types.
- Added new invocation type to test suite

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [x] This change requires a documentation update

## Checklist

### General Development Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [ ] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
- [ ] My changes properly handle rate limiting of the target service provider's
      API
- [ ] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [ ] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [ ] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2023-05-02 19:15 UTC, xdumaine approved these changes
nonblocking suggestions

2023-05-02 19:15 UTC, xdumaine commented on src/actions.ts
> +  return valid;
This seems a bit arcane - I don't think i've ever seen someone use `&&=` in code before, nor `'' < string` for string existence. It seems like it works, but can we just do this for more standard code?


```suggestion
  const { project, summary, classification } = (actionProperties || {});
  return !!project && !!summary && !!classification;
```

2023-05-02 19:15 UTC, xdumaine commented on src/actions.ts
> +type FullCreateIssueActionProperties = Omit<
This seems ok. instead of a parent union and an omit, I did kindof backwards from this,  to compose the union type instead of narrowing, if we want them to match exactly, but what you did is definitely compatible.

2023-05-02 19:17 UTC, plfx commented on src/actions.ts
> +  return valid;
It is arcane, yes. It has the benefit of asserting not just existence but also string-ness. Maybe we don't need to be that defensive. I can update.

2023-05-02 19:25 UTC, plfx commented on src/actions.ts
> +  return valid;
See newest changeset for something hopefully much less arcane.

2023-05-02 19:29 UTC, plfx commented on src/actions.ts
> +  return valid;
Actually, I'm wrong on this behavior. I'll remove the `<`.

2023-05-02 19:37 UTC, xdumaine submitted a review, later dismissed

2023-05-02 19:39 UTC, ryan-willis submitted a review, later dismissed

2023-05-02 19:47 UTC, Nick-NCSU requested changes

2023-05-02 19:47 UTC, Nick-NCSU commented on package.json
> +  "version": "3.9.0",
This repo is versioned using Auto. Info can be found in the README but in short, do not change this number manually and tag this PR with `minor` and `release`
```suggestion
  "version": "3.8.4",
```

2023-05-02 19:48 UTC, Nick-NCSU commented on package.json
> +  "version": "3.9.0",
https://github.com/JupiterOne/graph-jira#versioning-this-project

2023-05-02 21:27 UTC, zemberdotnet approved these changes

2023-05-02 21:27 UTC, zemberdotnet commented on src/actions.ts
> +      Key: actionDataS3Key,
Can the path to the object just be included as an s3 url in the payload?

2023-05-02 21:27 UTC, zemberdotnet commented on src/actions.ts
> +  s3Client: S3,
I think the fetching data from s3 part would be better suited to go in the deployment of this project.

2023-05-02 21:37 UTC, merged

2023-05-02 21:43 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v3.9.0`](https://github.com/JupiterOne/graph-jira/releases/tag/v3.9.0) :rocket:

2023-05-02 21:53 UTC, plfx commented on src/actions.ts
> +  s3Client: S3,
This makes sense. Janus team has a list of development follow-up actions after we resolve the issue. I will add that.

2023-05-03 15:24 UTC, xdumaine commented on src/actions.ts
> +      Key: actionDataS3Key,
Are you asking if we could use a presigned url instead of an object key and bucket?

2023-05-03 17:27 UTC, zemberdotnet commented on src/actions.ts
> +      Key: actionDataS3Key,
@xdumaine I mean the  S3 URI like: `s3://path/to/bucket/my-file`. This could be consumed by the action. Then it would not need to know anything about `jupiteroneEnv`.