Jira Enhancement 5.1.1
JupiterOne/graph-jira pull request #225
Opened 2024-06-27 16:57 UTC by poornima-metron

# Description

Thank you for contributing to a JupiterOne integration!

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.

## Summary

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## Checklist

### General Development Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [ ] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
- [ ] My changes properly handle rate limiting of the target service provider's
      API
- [ ] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [ ] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [ ] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2024-07-10 16:54 UTC, RonaldEAM requested changes

2024-07-10 16:54 UTC, RonaldEAM commented on src/config.ts
> +  },
Let's not use a different config field for this, should be handled within the existing "customFields" field

2024-07-10 16:54 UTC, RonaldEAM commented on src/converters/IssueEntityConverter.ts
> +  });
This implementation can be simplified with lodash `get` method and the field name formatting can also be simplified:
```typescript
  for (const path of complexCustomFieldsToInclude) {
    const [baseFieldId, ...rest] = path.split('.');
    const nestedPath = rest.join('.');
    if (!issue.fields[baseFieldId]) {
      continue;
    }
    const extractedValue = get(issue.fields[baseFieldId], nestedPath);
    if (!extractedValue) {
      continue;
    }
    const baseFieldName = camelCase(fieldsById[baseFieldId].name);
    const fieldName = nestedPath.split(/[\.\[\]]+/).map(camelCase).join('');
    customFields[`${baseFieldName}${fieldName}`] = extractedValue;
  }
```
Also this should be adapted to be inside the loop in line 105 because all custom fields should come in the  `customFields` config field. So you can verify first if it's a complex field and execute this logic, if it's not execute the logic for simple fields as it is.

2024-07-10 16:54 UTC, RonaldEAM commented on src/steps/issues.ts
> +  );
not necessary as these will be part of `customFields` config

2024-07-11 10:16 UTC, poornima-metron commented on src/config.ts
> +  },
removed **complexCustomFields**  from config

2024-07-11 10:16 UTC, poornima-metron commented on src/steps/issues.ts
> +  );
removed the log

2024-07-11 10:17 UTC, poornima-metron commented on src/converters/IssueEntityConverter.ts
> +  });
this makes sense, moved the suggested logic inside the loop and verifying if its a complex field or simple field

2024-07-12 21:05 UTC, RonaldEAM approved these changes

2024-07-22 15:15 UTC, merged

2024-07-22 15:21 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v5.2.0`](https://github.com/JupiterOne/graph-jira/releases/tag/v5.2.0) :rocket: