AB#5772 Custom field not getting ingested
JupiterOne/graph-jira pull request #90
Opened 2021-05-13 20:27 UTC by mknoedel

### Purpose
Auth0 ran into an issue where a custom field of type "NumberField" was not getting ingested in their integration runs. After looking into it, I found that we actually were not ingesting several different types of custom fields. 

### What I did
I made the Jira integration support all custom types: https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#setting-custom-field-data-for-other-field-types

2021-05-13 20:28 UTC, mknoedel commented on src/converters/IssueEntityConverter.test.ts
> +      // doc object field (idk where this is in the documentation)
These notes indicate what custom fields I will be testing below.

2021-05-13 20:28 UTC, mknoedel commented on src/converters/IssueEntityConverter.test.ts
> +    numberField: 1234,
number fields were not being parsed correctly prior to this change.

2021-05-13 20:29 UTC, mknoedel commented on src/converters/IssueEntityConverter.ts
> -function parseNumber(s: string | number): number | string {
moved this method to jira/parseContent.ts

2021-05-13 20:29 UTC, mknoedel commented on src/converters/IssueEntityConverter.ts
> -        if (typeof value === "string") {
Extracted this logic into extractValueFromCustomField

2021-05-13 20:31 UTC, mknoedel commented on src/converters/extractValueFromCustomField.ts
> +        { fieldValue: value },
I'm unsure if this is safe to do or not as it could potentially contain sensitive information

2021-05-14 01:26 UTC, austinkelleher requested changes
Left a few minor comments. I mainly just think we should remove the logging of the actual field value data. Nice work on all of the unit tests.

2021-05-14 01:26 UTC, austinkelleher commented on src/converters/extractValueFromCustomField.ts
> + * Each one stores information in a differnt way. This makes sure
Minor typo: `differnt` -> `different`

2021-05-14 01:26 UTC, austinkelleher commented on src/converters/extractValueFromCustomField.ts
> +        { fieldValue: value },
When we are unsure, might be best to edge on the side of caution and _not_ log it. It does seem like we'd be logging too much here. 

Additionally, I think we should keep this function pure and log from the caller instead of passing a logger.

2021-05-14 01:26 UTC, austinkelleher commented on src/converters/extractValueFromCustomField.test.ts
> +describe("extractValueFromCustomField", () => {
Nice unit tests!

2021-05-14 12:19 UTC, austinkelleher submitted a review, later dismissed

2021-05-14 12:22 UTC, austinkelleher commented on src/converters/IssueEntityConverter.ts
> +          logger.warn(`Unable to parse custom field ${fieldName}`);
Small feedback for awareness - I almost never use string interpolation when logging because it makes searching for these logs much slower. An object with the relevant properties as the first argument is the way to go.

Log searching for strings that **contain** `"Unable to parse custom field"` 
Is slower than **exact** matches

```ts
logger.warn({ fieldName }, 'Unable to parse custom field');
```

2021-05-14 12:26 UTC, austinkelleher approved these changes

2021-05-14 12:32 UTC, merged